//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaos.Portal.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Level { get; set; }
        public Nullable<System.Guid> SessionGUID { get; set; }
        public double Duration { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
