//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaos.Portal.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public string TableIdentifier { get; set; }
        public long Permission1 { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
