//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaos.Portal.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PortalEntities : DbContext
    {
        public PortalEntities() : base("name=PortalEntities")
        {
        }

        public PortalEntities( string connectionString ) : base( connectionString )
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClientSettings> ClientSettings { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Group_User_Join> Group_User_Join { get; set; }
        public DbSet<IndexSettings> IndexSettings { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Module> Module { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<Session> Session { get; set; }
        public DbSet<Subscription> Subscription { get; set; }
        public DbSet<Subscription_User_Join> Subscription_User_Join { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
        public DbSet<TicketType> TicketType { get; set; }
        public DbSet<UserSettings> UserSettings { get; set; }
        public DbSet<SessionInfo> SessionInfo { get; set; }
        public DbSet<SubscriptionInfo> SubscriptionInfo { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    
        public virtual ObjectResult<ClientSettings> ClientSettings_Get(byte[] gUID)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClientSettings>("ClientSettings_Get", gUIDParameter);
        }
    
        public virtual ObjectResult<ClientSettings> ClientSettings_Get(byte[] gUID, MergeOption mergeOption)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClientSettings>("ClientSettings_Get", mergeOption, gUIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ClientSettings_Set(byte[] gUID, string name, string settings)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var settingsParameter = settings != null ?
                new ObjectParameter("Settings", settings) :
                new ObjectParameter("Settings", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ClientSettings_Set", gUIDParameter, nameParameter, settingsParameter);
        }
    
        public virtual int Group_AssociateWithUser(byte[] groupGUID, byte[] userGUID, Nullable<int> permission, byte[] requestUserGUID, ObjectParameter errorCode)
        {
            var groupGUIDParameter = groupGUID != null ?
                new ObjectParameter("GroupGUID", groupGUID) :
                new ObjectParameter("GroupGUID", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            var permissionParameter = permission.HasValue ?
                new ObjectParameter("Permission", permission) :
                new ObjectParameter("Permission", typeof(int));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Group_AssociateWithUser", groupGUIDParameter, userGUIDParameter, permissionParameter, requestUserGUIDParameter, errorCode);
        }
    
        public virtual int Group_Create(byte[] gUID, string name, byte[] requestUserGUID, Nullable<int> systemPermission, ObjectParameter errorCode)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            var systemPermissionParameter = systemPermission.HasValue ?
                new ObjectParameter("SystemPermission", systemPermission) :
                new ObjectParameter("SystemPermission", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Group_Create", gUIDParameter, nameParameter, requestUserGUIDParameter, systemPermissionParameter, errorCode);
        }
    
        public virtual int Group_Delete(byte[] gUID, byte[] userGUID, ObjectParameter errorCode)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Group_Delete", gUIDParameter, userGUIDParameter, errorCode);
        }
    
        public virtual ObjectResult<Group> Group_Get(byte[] gUID, string name, byte[] requestUserGUID)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Group>("Group_Get", gUIDParameter, nameParameter, requestUserGUIDParameter);
        }
    
        public virtual ObjectResult<Group> Group_Get(byte[] gUID, string name, byte[] requestUserGUID, MergeOption mergeOption)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Group>("Group_Get", mergeOption, gUIDParameter, nameParameter, requestUserGUIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Group_Update(string newName, Nullable<int> newSystemPermission, byte[] whereGroupGUID, byte[] requestUserGUID)
        {
            var newNameParameter = newName != null ?
                new ObjectParameter("NewName", newName) :
                new ObjectParameter("NewName", typeof(string));
    
            var newSystemPermissionParameter = newSystemPermission.HasValue ?
                new ObjectParameter("NewSystemPermission", newSystemPermission) :
                new ObjectParameter("NewSystemPermission", typeof(int));
    
            var whereGroupGUIDParameter = whereGroupGUID != null ?
                new ObjectParameter("WhereGroupGUID", whereGroupGUID) :
                new ObjectParameter("WhereGroupGUID", typeof(byte[]));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Group_Update", newNameParameter, newSystemPermissionParameter, whereGroupGUIDParameter, requestUserGUIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> IndexSettings_Create(Nullable<int> iD, Nullable<int> moduleID, string settings)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var moduleIDParameter = moduleID.HasValue ?
                new ObjectParameter("ModuleID", moduleID) :
                new ObjectParameter("ModuleID", typeof(int));
    
            var settingsParameter = settings != null ?
                new ObjectParameter("Settings", settings) :
                new ObjectParameter("Settings", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("IndexSettings_Create", iDParameter, moduleIDParameter, settingsParameter);
        }
    
        public virtual ObjectResult<IndexSettings> IndexSettings_Get(Nullable<int> moduleID)
        {
            var moduleIDParameter = moduleID.HasValue ?
                new ObjectParameter("ModuleID", moduleID) :
                new ObjectParameter("ModuleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IndexSettings>("IndexSettings_Get", moduleIDParameter);
        }
    
        public virtual ObjectResult<IndexSettings> IndexSettings_Get(Nullable<int> moduleID, MergeOption mergeOption)
        {
            var moduleIDParameter = moduleID.HasValue ?
                new ObjectParameter("ModuleID", moduleID) :
                new ObjectParameter("ModuleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IndexSettings>("IndexSettings_Get", mergeOption, moduleIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Log_Create(string name, string level, byte[] sessionGUID, Nullable<double> duration, string message)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var levelParameter = level != null ?
                new ObjectParameter("Level", level) :
                new ObjectParameter("Level", typeof(string));
    
            var sessionGUIDParameter = sessionGUID != null ?
                new ObjectParameter("SessionGuid", sessionGUID) :
                new ObjectParameter("SessionGuid", typeof(byte[]));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("Duration", duration) :
                new ObjectParameter("Duration", typeof(double));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Log_Create", nameParameter, levelParameter, sessionGUIDParameter, durationParameter, messageParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Module_Create(Nullable<int> iD, string name, string configuration)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var configurationParameter = configuration != null ?
                new ObjectParameter("Configuration", configuration) :
                new ObjectParameter("Configuration", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Module_Create", iDParameter, nameParameter, configurationParameter);
        }
    
        public virtual ObjectResult<Module> Module_Get(Nullable<int> iD, string name)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Module>("Module_Get", iDParameter, nameParameter);
        }
    
        public virtual ObjectResult<Module> Module_Get(Nullable<int> iD, string name, MergeOption mergeOption)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Module>("Module_Get", mergeOption, iDParameter, nameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Session_Create(byte[] sessionGUID, byte[] userGUID)
        {
            var sessionGUIDParameter = sessionGUID != null ?
                new ObjectParameter("SessionGuid", sessionGUID) :
                new ObjectParameter("SessionGuid", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Session_Create", sessionGUIDParameter, userGUIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Session_Delete(byte[] sessionGUID, byte[] userGUID)
        {
            var sessionGUIDParameter = sessionGUID != null ?
                new ObjectParameter("SessionGuid", sessionGUID) :
                new ObjectParameter("SessionGuid", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Session_Delete", sessionGUIDParameter, userGUIDParameter);
        }
    
        public virtual ObjectResult<Session> Session_Get(byte[] sessionGUID, byte[] userGUID)
        {
            var sessionGUIDParameter = sessionGUID != null ?
                new ObjectParameter("SessionGuid", sessionGUID) :
                new ObjectParameter("SessionGuid", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Session>("Session_Get", sessionGUIDParameter, userGUIDParameter);
        }
    
        public virtual ObjectResult<Session> Session_Get(byte[] sessionGUID, byte[] userGUID, MergeOption mergeOption)
        {
            var sessionGUIDParameter = sessionGUID != null ?
                new ObjectParameter("SessionGuid", sessionGUID) :
                new ObjectParameter("SessionGuid", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Session>("Session_Get", mergeOption, sessionGUIDParameter, userGUIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Session_Update(byte[] userGUID, byte[] whereSessionGUID, byte[] whereUserGUID)
        {
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            var whereSessionGUIDParameter = whereSessionGUID != null ?
                new ObjectParameter("WhereSessionGUID", whereSessionGUID) :
                new ObjectParameter("WhereSessionGUID", typeof(byte[]));
    
            var whereUserGUIDParameter = whereUserGUID != null ?
                new ObjectParameter("WhereUserGUID", whereUserGUID) :
                new ObjectParameter("WhereUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Session_Update", userGUIDParameter, whereSessionGUIDParameter, whereUserGUIDParameter);
        }
    
        public virtual ObjectResult<SubscriptionInfo> SubscriptionInfo_Get(byte[] gUID, byte[] requestUserGUID)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubscriptionInfo>("SubscriptionInfo_Get", gUIDParameter, requestUserGUIDParameter);
        }
    
        public virtual ObjectResult<SubscriptionInfo> SubscriptionInfo_Get(byte[] gUID, byte[] requestUserGUID, MergeOption mergeOption)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubscriptionInfo>("SubscriptionInfo_Get", mergeOption, gUIDParameter, requestUserGUIDParameter);
        }
    
        public virtual int Subscription_Create(byte[] gUID, string name, byte[] requestUserGUID, ObjectParameter errorCode)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Subscription_Create", gUIDParameter, nameParameter, requestUserGUIDParameter, errorCode);
        }
    
        public virtual int Subscription_Delete(byte[] subscriptionGUID, byte[] requestUserGUID, ObjectParameter errorCode)
        {
            var subscriptionGUIDParameter = subscriptionGUID != null ?
                new ObjectParameter("SubscriptionGUID", subscriptionGUID) :
                new ObjectParameter("SubscriptionGUID", typeof(byte[]));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Subscription_Delete", subscriptionGUIDParameter, requestUserGUIDParameter, errorCode);
        }
    
        public virtual int Subscription_Update(byte[] gUID, string newName, byte[] requestUserGUID, ObjectParameter errorCode)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var newNameParameter = newName != null ?
                new ObjectParameter("NewName", newName) :
                new ObjectParameter("NewName", typeof(string));
    
            var requestUserGUIDParameter = requestUserGUID != null ?
                new ObjectParameter("RequestUserGUID", requestUserGUID) :
                new ObjectParameter("RequestUserGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Subscription_Update", gUIDParameter, newNameParameter, requestUserGUIDParameter, errorCode);
        }
    
        public virtual ObjectResult<Nullable<int>> Ticket_Create(byte[] gUID, Nullable<int> ticketTypeID, string xML, string callback)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var ticketTypeIDParameter = ticketTypeID.HasValue ?
                new ObjectParameter("TicketTypeID", ticketTypeID) :
                new ObjectParameter("TicketTypeID", typeof(int));
    
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            var callbackParameter = callback != null ?
                new ObjectParameter("Callback", callback) :
                new ObjectParameter("Callback", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Ticket_Create", gUIDParameter, ticketTypeIDParameter, xMLParameter, callbackParameter);
        }
    
        public virtual ObjectResult<Ticket> Ticket_Get(byte[] gUID)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ticket>("Ticket_Get", gUIDParameter);
        }
    
        public virtual ObjectResult<Ticket> Ticket_Get(byte[] gUID, MergeOption mergeOption)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ticket>("Ticket_Get", mergeOption, gUIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Ticket_Use(byte[] whereGUID)
        {
            var whereGUIDParameter = whereGUID != null ?
                new ObjectParameter("WhereGUID", whereGUID) :
                new ObjectParameter("WhereGUID", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Ticket_Use", whereGUIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> User_Create(byte[] gUID, string email)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("User_Create", gUIDParameter, emailParameter);
        }
    
        public virtual ObjectResult<User> User_Get(byte[] gUID)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("User_Get", gUIDParameter);
        }
    
        public virtual ObjectResult<User> User_Get(byte[] gUID, MergeOption mergeOption)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("User_Get", mergeOption, gUIDParameter);
        }
    
        public virtual ObjectResult<UserInfo> UserInfo_Get(byte[] gUID, byte[] sessionGUID, string email)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var sessionGUIDParameter = sessionGUID != null ?
                new ObjectParameter("SessionGuid", sessionGUID) :
                new ObjectParameter("SessionGuid", typeof(byte[]));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserInfo>("UserInfo_Get", gUIDParameter, sessionGUIDParameter, emailParameter);
        }
    
        public virtual ObjectResult<UserInfo> UserInfo_Get(byte[] gUID, byte[] sessionGUID, string email, MergeOption mergeOption)
        {
            var gUIDParameter = gUID != null ?
                new ObjectParameter("Guid", gUID) :
                new ObjectParameter("Guid", typeof(byte[]));
    
            var sessionGUIDParameter = sessionGUID != null ?
                new ObjectParameter("SessionGuid", sessionGUID) :
                new ObjectParameter("SessionGuid", typeof(byte[]));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserInfo>("UserInfo_Get", mergeOption, gUIDParameter, sessionGUIDParameter, emailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UserSettings_Set(byte[] clientSettingsGUID, byte[] userGUID, string settings)
        {
            var clientSettingsGUIDParameter = clientSettingsGUID != null ?
                new ObjectParameter("ClientSettingsGUID", clientSettingsGUID) :
                new ObjectParameter("ClientSettingsGUID", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            var settingsParameter = settings != null ?
                new ObjectParameter("Settings", settings) :
                new ObjectParameter("Settings", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UserSettings_Set", clientSettingsGUIDParameter, userGUIDParameter, settingsParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UserSettings_Delete(byte[] clientSettingsGUID, byte[] userGUID)
        {
            var clientSettingsGUIDParameter = clientSettingsGUID != null ?
                new ObjectParameter("ClientSettingsGUID", clientSettingsGUID) :
                new ObjectParameter("ClientSettingsGUID", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UserSettings_Delete", clientSettingsGUIDParameter, userGUIDParameter);
        }
    
        public virtual ObjectResult<UserSettings> UserSettings_Get(byte[] clientSettingsGUID, byte[] userGUID)
        {
            var clientSettingsGUIDParameter = clientSettingsGUID != null ?
                new ObjectParameter("ClientSettingsGUID", clientSettingsGUID) :
                new ObjectParameter("ClientSettingsGUID", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserSettings>("UserSettings_Get", clientSettingsGUIDParameter, userGUIDParameter);
        }
    
        public virtual ObjectResult<UserSettings> UserSettings_Get(byte[] clientSettingsGUID, byte[] userGUID, MergeOption mergeOption)
        {
            var clientSettingsGUIDParameter = clientSettingsGUID != null ?
                new ObjectParameter("ClientSettingsGUID", clientSettingsGUID) :
                new ObjectParameter("ClientSettingsGUID", typeof(byte[]));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGuid", userGUID) :
                new ObjectParameter("UserGuid", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserSettings>("UserSettings_Get", mergeOption, clientSettingsGUIDParameter, userGUIDParameter);
        }
    }
}
