//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaos.Portal.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription_User_Join
    {
        public System.Guid SubscriptionGUID { get; set; }
        public System.Guid UserGUID { get; set; }
        public long Permission { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual User User { get; set; }
    }
}
