//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaos.Portal.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public System.Guid GUID { get; set; }
        public long TicketTypeID { get; set; }
        public string XML { get; set; }
        public string Callback { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
    
        public virtual TicketType TicketType { get; set; }
    }
}
