//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaos.Portal.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> SessionGUID { get; set; }
        public Nullable<long> SystemPermission { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> SessionDateCreated { get; set; }
    }
}
