<?xml version="1.0" encoding="utf-8"?><Database Name="Portal" Class="PortalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.56.101;Initial Catalog=Portal;Persist Security Info=True;User ID=sa" SettingsObjectName="Geckon.Portal.Data.Properties.Settings" SettingsPropertyName="PortalConnectionString7" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AuthenticationProvider" Member="AuthenticationProviders">
    <Type Name="AuthenticationProvider">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="AssemblyPath" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Association Name="AuthenticationProvider_AuthenticationProvider_User_Join" Member="AuthenticationProvider_User_Joins" ThisKey="ID" OtherKey="AuthenticationProviderID" Type="AuthenticationProvider_User_Join" />
    </Type>
  </Table>
  <Table Name="dbo.XmlType" Member="XmlTypes">
    <Type Name="XmlType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Association Name="XmlType_ClientSetting" Member="ClientSettings" ThisKey="ID" OtherKey="XmlTypeID" Type="ClientSetting" />
    </Type>
  </Table>
  <Table Name="dbo.AuthenticationProvider_User_Join" Member="AuthenticationProvider_User_Joins">
    <Type Name="AuthenticationProvider_User_Join" Id="ID5">
      <Column Name="AuthenticationProviderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UniqueIdentifier" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="AuthenticationProvider_AuthenticationProvider_User_Join" Member="AuthenticationProvider" ThisKey="AuthenticationProviderID" OtherKey="ID" Type="AuthenticationProvider" IsForeignKey="true" />
      <Association Name="User_AuthenticationProvider_User_Join" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ClientSetting" Member="ClientSettings">
    <Type Name="ClientSetting">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="XmlTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ClientSetting_Session" Member="Sessions" ThisKey="ID" OtherKey="ClientSettingID" Type="Session" />
      <Association Name="XmlType_ClientSetting" Member="XmlType" ThisKey="XmlTypeID" OtherKey="ID" Type="XmlType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Groups">
    <Type Name="Group" Id="ID7">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreadted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Group_Group_User_Join" Member="Group_User_Joins" ThisKey="ID" OtherKey="GroupID" Type="Group_User_Join" />
    </Type>
  </Table>
  <Table Name="dbo.Group_User_Join" Member="Group_User_Joins">
    <Type Name="Group_User_Join" Id="ID8">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Group_Group_User_Join" Member="Group" ThisKey="GroupID" OtherKey="ID" Type="Group" IsForeignKey="true" />
      <Association Name="User_Group_User_Join" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Module" Member="Modules">
    <Type Name="Module" Id="ID2">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Configuration" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Path" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permissions">
    <Type Name="Permission">
      <Column Name="TableIdentifier" Type="System.String" DbType="VarChar(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RightName" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Permission" Member="Permission1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RelationType" Member="RelationTypes">
    <Type Name="RelationType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Session" Member="Sessions">
    <Type Name="Session" Id="ID1">
      <Column Name="SessionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientSettingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ClientSetting_Session" Member="ClientSetting" ThisKey="ClientSettingID" OtherKey="ID" Type="ClientSetting" IsForeignKey="true" />
      <Association Name="User_Session" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subscription" Member="Subscriptions">
    <Type Name="Subscription" Id="ID9">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Subscription_Subscription_User_Join" Member="Subscription_User_Joins" ThisKey="ID" OtherKey="SubscriptionID" Type="Subscription_User_Join" />
    </Type>
  </Table>
  <Table Name="dbo.Subscription_User_Join" Member="Subscription_User_Joins">
    <Type Name="Subscription_User_Join">
      <Column Name="SubscriptionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Subscription_Subscription_User_Join" Member="Subscription" ThisKey="SubscriptionID" OtherKey="ID" Type="Subscription" IsForeignKey="true" />
      <Association Name="User_Subscription_User_Join" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubsystemRelation" Member="SubsystemRelations">
    <Type Name="SubsystemRelation">
      <Column Name="Object1Type" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Object1Field" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Object1Value" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Object2Type" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Object2Field" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Object2Value" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UniqueIdentifier" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User" Id="ID6">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Middlename" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="User_AuthenticationProvider_User_Join" Member="AuthenticationProvider_User_Joins" ThisKey="ID" OtherKey="UserID" Type="AuthenticationProvider_User_Join" />
      <Association Name="User_Group_User_Join" Member="Group_User_Joins" ThisKey="ID" OtherKey="UserID" Type="Group_User_Join" />
      <Association Name="User_Session" Member="Sessions" ThisKey="ID" OtherKey="UserID" Type="Session" />
      <Association Name="User_Subscription_User_Join" Member="Subscription_User_Joins" ThisKey="ID" OtherKey="UserID" Type="Subscription_User_Join" />
    </Type>
  </Table>
  <Table Name="dbo.SessionInfo" Member="SessionInfos">
    <Type Name="SessionInfo">
      <Column Name="SessionID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientSettingID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MinutesSinceRenewal" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserInfo" Member="UserInfos">
    <Type Name="UserInfo" Id="ID4">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SessionID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Middlename" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ClientSettingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SessionDateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Extension" Member="Extensions">
    <Type Name="Extension" Id="ID3">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Map" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.Session_Update" Method="Session_Update">
    <Parameter Name="SessionID" Parameter="sessionID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserGUID" Parameter="userGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="ClientSettingID" Parameter="clientSettingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="WhereSessionID" Parameter="whereSessionID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="WhereUserGUID" Parameter="whereUserGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="WhereClientSettingID" Parameter="whereClientSettingID" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.Session_Delete" Method="Session_Delete">
    <Parameter Name="SessionID" Parameter="sessionID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClientSettingID" Parameter="clientSettingID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Module_Get" Method="Module_Get">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.Module_Insert" Method="Module_Insert">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Configuration" Parameter="configuration" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="VarChar(1024)" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.Session_Insert" Method="Session_Insert">
    <Parameter Name="SessionID" Parameter="sessionID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserGUID" Parameter="userGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="ClientSettingID" Parameter="clientSettingID" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.Extension_Get" Method="Extension_Get">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Map" Parameter="map" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.Extension_Insert" Method="Extension_Insert">
    <Parameter Name="Map" Parameter="map" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Fullname" Parameter="fullname" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Path" Parameter="path" Type="System.String" DbType="VarChar(1024)" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.User_Delete" Method="User_Delete">
    <Parameter Name="GUID" Parameter="gUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Session_Get" Method="Session_Get">
    <Parameter Name="SessionID" Parameter="sessionID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ClientSettingID" Parameter="clientSettingID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalCount" Parameter="totalCount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.UserInfo_Get" Method="UserInfo_Get">
    <Parameter Name="GUID" Parameter="gUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="SessionID" Parameter="sessionID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="AuthenticationProviderUniqueidentifier" Parameter="authenticationProviderUniqueidentifier" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="AuthenticationProviderGUID" Parameter="authenticationProviderGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.AuthenticationProvider_User_Join_Get" Method="AuthenticationProvider_User_Join_Get">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AuthenticationProviderID" Parameter="authenticationProviderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UniqueIdentifier" Parameter="uniqueIdentifier" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID5" />
  </Function>
  <Function Name="dbo.User_AssociateWithAuthenticationProvider" Method="User_AssociateWithAuthenticationProvider">
    <Parameter Name="UserGUID" Parameter="userGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="AuthenticationProviderGUID" Parameter="authenticationProviderGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UniqueIdentifier" Parameter="uniqueIdentifier" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID5" />
  </Function>
  <Function Name="dbo.User_Insert" Method="User_Insert">
    <Parameter Name="GUID" Parameter="gUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Firstname" Parameter="firstname" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Middlename" Parameter="middlename" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Lastname" Parameter="lastname" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID6" />
  </Function>
  <Function Name="dbo.User_Update" Method="User_Update">
    <Parameter Name="WhereGUID" Parameter="whereGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="NewGUID" Parameter="newGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="NewFirstname" Parameter="newFirstname" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="NewMiddlename" Parameter="newMiddlename" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="NewLastname" Parameter="newLastname" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Newemail" Parameter="newemail" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID6" />
  </Function>
  <Function Name="dbo.PopulateWithDefaultData" Method="PopulateWithDefaultData">
    <ElementType Name="PopulateWithDefaultDataResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Group_Get" Method="Group_Get">
    <Parameter Name="GroupGUID" Parameter="groupGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserGUID" Parameter="userGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType IdRef="ID7" />
  </Function>
  <Function Name="dbo.Group_Insert" Method="Group_Insert">
    <Parameter Name="GUID" Parameter="gUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType IdRef="ID7" />
  </Function>
  <Function Name="dbo.AssociateUserWithGroup" Method="AssociateUserWithGroup">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GroupID" Parameter="groupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserGUID" Parameter="userGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="GroupGUID" Parameter="groupGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Permission" Parameter="permission" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID8" />
  </Function>
  <Function Name="dbo.Group_Delete" Method="Group_Delete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="GUID" Parameter="gUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserGUID" Parameter="userGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Group_Update" Method="Group_Update">
    <Parameter Name="NewName" Parameter="newName" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="GroupID" Parameter="groupID" Type="System.Int32" DbType="Int" />
    <Parameter Name="GroupGUID" Parameter="groupGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserGUID" Parameter="userGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="ErrorCode" Parameter="errorCode" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType IdRef="ID7" />
  </Function>
  <Function Name="dbo.Subscription_Get" Method="Subscription_Get">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="GUID" Parameter="gUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="RequestUserID" Parameter="requestUserID" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID9" />
  </Function>
  <Function Name="dbo.Subscription_Delete" Method="Subscription_Delete">
    <Parameter Name="SubscriptionID" Parameter="subscriptionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubscriptionGUID" Parameter="subscriptionGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="RequestUserID" Parameter="requestUserID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Subscription_Insert" Method="Subscription_Insert">
    <Parameter Name="GUID" Parameter="gUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <ElementType IdRef="ID9" />
  </Function>
  <Function Name="dbo.Subscription_Delete" Method="Subscription_Delete1">
    <Parameter Name="SubscriptionID" Parameter="subscriptionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubscriptionGUID" Parameter="subscriptionGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="RequestUserID" Parameter="requestUserID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Subscription_Update" Method="Subscription_Update">
    <Parameter Name="SubscriptionID" Parameter="subscriptionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubscriptionGUID" Parameter="subscriptionGUID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="NewName" Parameter="newName" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="RequestUserID" Parameter="requestUserID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>