ALTER TABLE `Group_User_Join` 
DROP FOREIGN KEY `FK_Group_User_Join_UserGUID_User_GUID`,
DROP FOREIGN KEY `FK_Group_User_Join_GroupGUID_Group_GUID`;
ALTER TABLE `Group_User_Join` 
ADD CONSTRAINT `FK_Group_User_Join_UserGUID_User_GUID`
  FOREIGN KEY (`UserGUID`)
  REFERENCES `User` (`GUID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `FK_Group_User_Join_GroupGUID_Group_GUID`
  FOREIGN KEY (`GroupGUID`)
  REFERENCES `Group` (`GUID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
